import type { Metadata } from "next";
import { Geist, Geist_Mono, Genos, Baumans } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const genos = Genos({
  variable: "--font-genos",
  subsets: ["latin"],
  weight: "400",
});

const baumans = Baumans({
  variable: "--font-baumans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${genos.variable} ${baumans.variable} antialiased`}
      >
      <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
