const location = [
    {
        division: "Dhaka",
        name: "Dhaka",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Dhaka",
        name: "Faridpur",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Dhaka",
        name: "Gazipur",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Dhaka",
        name: "Gopalganj",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Dhaka",
        name: "Kishoreganj",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Dhaka",
        name: "Madaripur",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Dhaka",
        name: "Manikganj",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Dhaka",
        name: "Munshiganj",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Dhaka",
        name: "Narayanganj",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Dhaka",
        name: "Narsingdi",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Dhaka",
        name: "Rajbari",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Dhaka",
        name: "Shariatpur",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Dhaka",
        name: "Tangail",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Chattogram",
        name: "Bandarban",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Chattogram",
        name: "Brahmanbaria",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Chattogram",
        name: "Chandpur",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Chattogram",
        name: "Chattogram",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Chattogram",
        name: "Cumilla",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Chattogram",
        name: "Cox's Bazar",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Chattogram",
        name: "Feni",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Chattogram",
        name: "Khagrachari",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Chattogram",
        name: "Lakshmipur",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Chattogram",
        name: "Noakhali",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Chattogram",
        name: "Rangamati",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Rajshahi",
        name: "Bogura",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Rajshahi",
        name: "Joypurhat",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Rajshahi",
        name: "Naogaon",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Rajshahi",
        name: "Natore",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Rajshahi",
        name: "Chapainawabganj",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Rajshahi",
        name: "Pabna",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Rajshahi",
        name: "Rajshahi",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Rajshahi",
        name: "Sirajganj",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Khulna",
        name: "Bagerhat",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Khulna",
        name: "Chuadanga",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Khulna",
        name: "Jashore",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Khulna",
        name: "Jhenaidah",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Khulna",
        name: "Khulna",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Khulna",
        name: "Kushtia",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Khulna",
        name: "Magura",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Khulna",
        name: "Meherpur",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Khulna",
        name: "Narail",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Khulna",
        name: "Satkhira",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Barisal",
        name: "Barguna",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Barisal",
        name: "Barisal",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Barisal",
        name: "Bhola",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Barisal",
        name: "Jhalokathi",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Barisal",
        name: "Patuakhali",
        available: true,
        phone: ["01911589470", "09845945"],
        address: "Opposite to Gabtoli Bus Terminal, Dhaka",
    },
    {
        division: "Barisal",
        name: "Pirojpur",
        available: true,
        phone: ["01711581230"],
        address: "Near Gazipur Chowrasta, Gazipur",
    },
    {
        division: "Sylhet",
        name: "Habiganj",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Sylhet",
        name: "Moulvibazar",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Sylhet",
        name: "Sunamganj",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Sylhet",
        name: "Sylhet",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Rangpur",
        name: "Dinajpur",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Rangpur",
        name: "Gaibandha",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Rangpur",
        name: "Kurigram",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Rangpur",
        name: "Lalmonirhat",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Rangpur",
        name: "Nilphamari",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Rangpur",
        name: "Panchagarh",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Rangpur",
        name: "Rangpur",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Rangpur",
        name: "Thakurgaon",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Mymensingh",
        name: "Jamalpur",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
    {
        division: "Mymensingh",
        name: "Mymensingh",
        available: false,
        phone: [],
        address: "Branch under development",
    },
    {
        division: "Mymensingh",
        name: "Netrokona",
        available: true,
        phone: ["01911222333"],
        address: "In front of Feni Stadium Gate",
    },
    {
        division: "Mymensingh",
        name: "Sherpur",
        available: true,
        phone: ["01811581235"],
        address: "Opposite to Bandarban Bus Terminal",
    },
];

const distance =[
    {
        IntraLocal: 0.5,
        Local: 1,
        IntraDivision: 1.3,
        Capital: 1.7,
        Remote: 2,
        Divisional: 2.3,
        InterDivision: 2.4,
        CrossCapital: 2.5
    }
]

export const ProductTypeList = [
  { name: "Document", value: 1 },
  { name: "Clothing", value: 1 },
  { name: "Electronics", value: 1 },
  { name: "Food", value: 2 },
  { name: "Medicine", value: 3 },
  { name: "Grocery", value: 3 },
  { name: "GiftParcel", value: 3 },
  { name: "JeweleryHighValues", value: 3 },
  { name: "Books", value: 2 },
  { name: "Fragile", value: 3 },
  { name: "Others", value: 3 },
];
